name: ci

on:
  push:
    branches: [main]

permissions:
  actions: read # Lecture du code pour actions/checkout
  packages: write # Authentification + Publication vers GHCR

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Ruff Lint
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "check --output-format junit --output-file lint-report.xml"

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          project-path: devbox-ci.json

      - name: Run units tests with coverage
        run: devbox run --config devbox-ci.json units-tests

      - name: Run regression tests
        run: devbox run --config devbox-ci.json regression-tests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # Permet le build multi-platform images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Permet le build multi-platform images

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # user GitHub
          password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }} # PAT avec repo + package permissions

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true # Pour charger l'image localement
          tags: |
            ghcr.io/${{ github.actor }}/todolist:latest

      - name: Smoke Test
        run: devbox run --config devbox-ci.json smoke-test
        env:
          IMAGE: ghcr.io/${{ github.actor }}/todolist:latest
          NAME: todolist-smoke-${{ github.run_id }}

      - name: Multi-platform build and push the image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/todolist:latest

      - name: Upload all reports and artifacts
        uses: actions/upload-artifact@v4
        if: always() # Upload artifacts even if tests fail
        with:
          name: ci-reports-${{ github.run_id }}
          path: |
            lint-report.xml
            units-test-report.html
            regression-test-report.html
            coverage-html/
          retention-days: 7
