apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: todolist-gateway
  labels:
    app.kubernetes.io/name: todolist
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: "todolist.127.0.0.1.sslip.io"
    - name: https
      port: 443
      protocol: HTTPS
      hostname: "todolist.127.0.0.1.sslip.io"
      tls:
        mode: Terminate
        certificateRefs:
          - name: todolist-tls
