apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todolist
  labels:
    app.kubernetes.io/name: todolist
spec:
  ingressClassName: nginx
  rules:
    - host: todolist.127.0.0.1.sslip.io
      http:
        paths:
          - backend:
              service:
                name: todolist
                port:
                  number: 5000
            path: /
            pathType: Prefix
